//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodBook
    {
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string BloodGroup { get; set; }
        public string PhoneNumber { get; set; }
        public string Relation { get; set; }
        public int UserId { get; set; }
    
        public virtual userInfo userInfo { get; set; }
    }
}
