//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationReply
    {
        public int replyId { get; set; }
        public int RequestId { get; set; }
        public string willDonate { get; set; }
    
        public virtual RequestBlood RequestBlood { get; set; }
    }
}
