//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlagPost
    {
        public int FlagId { get; set; }
        public int PostID { get; set; }
        public int userID { get; set; }
        public string FlagReason { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual userInfo userInfo { get; set; }
    }
}
