//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BloodDonationDBEntities12 : DbContext
    {
        public BloodDonationDBEntities12()
            : base("name=BloodDonationDBEntities12")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bannedUser> bannedUsers { get; set; }
        public virtual DbSet<BloodBook> BloodBooks { get; set; }
        public virtual DbSet<contactU> contactUs { get; set; }
        public virtual DbSet<DisabledAccount> DisabledAccounts { get; set; }
        public virtual DbSet<DonationForSystem> DonationForSystems { get; set; }
        public virtual DbSet<FlagPost> FlagPosts { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<RequestBlood> RequestBloods { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<userInfo> userInfoes { get; set; }
        public virtual DbSet<DonationReply> DonationReplies { get; set; }
        public virtual DbSet<donorRating> donorRatings { get; set; }
    }
}
