//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int ReportId { get; set; }
        public string Report1 { get; set; }
        public int DonorId { get; set; }
        public int UserId { get; set; }
    
        public virtual userInfo userInfo { get; set; }
        public virtual userInfo userInfo1 { get; set; }
    }
}
