//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestBlood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestBlood()
        {
            this.DonationReplies = new HashSet<DonationReply>();
        }
    
        public int RequestId { get; set; }
        public string Request_Message { get; set; }
        public int UserId { get; set; }
        public int DonarId { get; set; }
    
        public virtual userInfo userInfo { get; set; }
        public virtual userInfo userInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationReply> DonationReplies { get; set; }
    }
}
